name: Deploy Application

on :
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application 
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0 
        with:
          docker_name: 'ghcr io/zaproxy/zaproxy:stable' 
          target: 'https://ticket-system-e6jz.onrender.com'
          cmd_options: '-a' 
          allow_issue_writing: false